# Generated by Django 5.1.3 on 2024-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text_area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
